import dotenv from "dotenv";
import fs from "fs";
import path from "path";
export type EnvTypeDefsConfig = {
  watch?: boolean;
};
const directoryPath = process.cwd();
const envTypePath = "env.d.ts";

type envT = {
  [key: string]: string;
};
const targetRegExp = new RegExp(/^\.env(\..+)?$/);
const envs: envT = {};

const getEnvPath = () => {
  try {
    const files = fs.readdirSync(directoryPath);
    const envFiles = files.filter((file) => {
      const stats = fs.statSync(file);
      if (stats.isFile() && file.match(targetRegExp)) {
        return file;
      }
    });
    if (envFiles.length == 0) {
      // [LOGS] No Env File Found in the current directory
    }
    return envFiles;
  } catch (error) {
    console.warn("> Unable to scan directory:");
    return [];
  }
};

function determineType(value: any) {
  if (value === "true" || value === "false") {
    return "boolean";
  } else if (!isNaN(value)) {
    return "number";
  } else if (value.match(/^[A-Za-z0-9+/=]*$/)) {
    return "string";
  } else {
    return "string";
  }
}

const envTypeDefs = (config?: EnvTypeDefsConfig) => {
  const envFiles = getEnvPath();
  envFiles.forEach((env) => {
    const envPath = path.join(directoryPath, env);
    const envConfig = dotenv.parse(fs.readFileSync(envPath));
    // insert config keys and values paris as (type);
    Object.keys(envConfig).forEach((key: string) => {
      envs[key] = determineType(envConfig[key]);
    });
  });
  //   write to env file
  const envPathName = path.join(directoryPath, envTypePath);
  let envObject = "";
  const envObjKeys = Object.keys(envs);
  envObjKeys.forEach((key, index) => {
    envObject += "\t" + key + ":" + envs[key];
    if (index != envObjKeys.length - 1) {
      envObject += ",\n\t";
    }
  });
  fs.writeFileSync(
    envPathName,
    `// generated by env-type-defs https://www.npmjs.com/package/env-type-defs
declare global {
  namespace NodeJS {
    interface ProcessEnv {
  ${envObject}
    }
  }
}
export {};
  `,
    {}
  );

  if (config?.watch) {
    const envFiles = getEnvPath();
    envFiles.forEach((envFile) => {
      const envFilePath = path.join(directoryPath, envFile);
      fs.watchFile(envFilePath, (curr, prev) => {
        if (curr.mtime !== prev.mtime) {
          // [LOGS] File changed, reloading env type definitions
          envTypeDefs(config);
        }
      });
    });
    //[LOGS] Waching for chnages
  }

  return envs;
};

envTypeDefs();
export default envTypeDefs;
