// generated by env-type-defs https://www.npmjs.com/package/env-type-defs
declare global {
  namespace NodeJS {
    interface ProcessEnv {
  	NODE_ENV:string,
		PORT:number,
		NEXT_PUBLIC_API_URL:string,
		NEXT_PUBLIC_WEBSOCKET_URL:string,
		NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:string,
		NEXT_PUBLIC_GOOGLE_ANALYTICS_ID:string,
		NEXT_PUBLIC_SENTRY_DSN:string,
		PAY:string,
		HOME:string,
		NEXT_PUBLIC_STRIPE_SECRET_KEY:string,
		NEXT_PUBLIC_APP_NAME:string,
		NEXT_PUBLIC_APP_VERSION:string,
		NEXT_PUBLIC_APP_DESCRIPTION:string,
		NEXT_PUBLIC_APP_AUTHOR:string,
		NEXT_PUBLIC_APP_AUTHOR_EMAIL:number
    }
  }
}
export {};
  