// generated by env-type-defs https://www.npmjs.com/package/env-type-defs
declare global {
  namespace NodeJS {
    interface ProcessEnv {
  	NODE_ENV:string,
		PORT:number,
		NEXT_PUBLIC_API_URL:string,
		NEXT_PUBLIC_WEBSOCKET_URL:string,
		NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:string,
		NEXT_PUBLIC_GOOGLE_ANALYTICS_ID:string,
		NEXT_PUBLIC_SENTRY_DSN:string,
		NEXT_PUBLIC_SENTRY_ENVIRONMENT:string,
		NEXT_PUBLIC_SENTRY_RELEASE:string,
		NEXT_PUBLIC_FEATURE_FLAG_EXAMPLE:boolean,
		NEXT_PUBLIC_ANALYTICS_ENABLED:boolean,
		NEXT_PUBLIC_APP_NAME:string,
		NEXT_PUBLIC_APP_VERSION:string,
		NEXT_PUBLIC_APP_DESCRIPTION:string,
		NEXT_PUBLIC_APP_AUTHOR:string,
		NEXT_PUBLIC_APP_AUTHOR_EMAIL:number,
		NEXT_PUBLIC_APP_AUTHOR_URL:string,
		NEXT_PUBLIC_APP_COPYRIGHT:string,
		NEXT_PUBLIC_APP_LOGO_URL:string,
		NEXT_PUBLIC_APP_FAVICON_URL:string,
		NEXT_PUBLIC_APP_THEME_COLOR:string
    }
  }
}
export {};
  